---
# Source: reactReduxChart/templates/react_redux_service.yml
apiVersion: v1
kind: Service
metadata:
  name: react-redux-app
  labels:
    run: react-redux-app
spec:
  ports:
  - port: 9000
    targetPort: 4100
  selector:
    run: react-redux-app
  type: LoadBalancer
---
# Source: reactReduxChart/templates/react_redux_deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-redux-app
  labels:
    run: react-redux-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: react-redux-app
  template:
    metadata:
      labels:
        run: react-redux-app
    spec:
      containers:
      - name: react-redux-app
        image: dpizar/react-redux:latest
        ports:
        - containerPort: 4100
