apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-redux-app
  labels:
    run: react-redux-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: react-redux-app
  template:
    metadata:
      labels:
        run: react-redux-app
    spec:
      containers:
        image: dpizar/reac-redux:latest
        name: react-redux-app
        ports:
        - containerPort: 4100