name: GKE Infrastructure

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch and only when Dockerfile is involved
  push:
    paths:
      - 'run-modules/**.tf'
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'run-modules/**.tf'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TAG: dpizar/gke-infrastructure:latest

jobs:
  dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
    
      - name: Login Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: ${{ env.TAG }}
          secrets: |
            "GCP_CREDENTIAL=${{ secrets.GCP_CREDENTIAL }}"
            "TERRAFORM_CREDENTIAL=${{ secrets.TERRAFORM_CREDENTIAL }}"
            "TFVARS=${{ secrets.TFVARS }}"
            
      - name: Run Infrastructure image
        run: |
          docker run --rm ${{ env.TEST_TAG }}
        
  prod:
    runs-on: ubuntu-latest
    #needs approval
    environment:
      name: prod
    steps:

      - name: Login Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: ${{ env.TAG }}
          secrets: |
            "GCP_CREDENTIAL=${{ secrets.GCP_CREDENTIAL }}"
            "TERRAFORM_CREDENTIAL=${{ secrets.TERRAFORM_CREDENTIAL }}"
            "TFVARS=${{ secrets.TFVARS }}"
            
      - name: Run Infrastructure image
        run: |
          docker run --rm ${{ env.TEST_TAG }}